### PR TITLE
Pls Refactor B4 Merge - UI Update (Multi Login Option) & Docker Build Dependency Verifier

### PR DESCRIPTION
**Pull request by rm4453**
# Description

[PR Description]

**Pls Refactor B4 Merge - UI Update (Multi Login Option) & Docker Build Dependency Verifier**

This pull request aims to improve the current user interface (UI) by introducing a multi-login option and implementing a Docker build dependency verifier. The changes proposed in this pull request offer more flexibility in configuring the application and enhance the setup process for administrators and users.

**UI Update:**

- The ability to choose a new configuration path will be introduced by deleting the ".cfgi" file.
- Resetting the admin account and all other user accounts will be made possible by deleting the "users.json" file.
- A new workflow will be established where deleting the ".cfgi" file while preserving user credentials eliminates the need to set up the admin account each time. Similarly, deleting the "users.json" file while retaining the configuration avoids the necessity of configuring the application repeatedly.

Please note the available setup config options:

1. **No Login** (Current functionality)
   - The application operates without requiring user login.

2. **Single-User Login** (1 Admin User)
   - Only one admin user is allowed to log in.

3. **Multi-User Private Registration** (Multiple Users + Admin Account Creation)
   - Multiple users can register, and the admin has the privilege to create user accounts.

4. **Multi-User Public Registration** (Multiple Users + Admin-Enabled/Disabled Public Registration)
   - Multiple users can register, and the admin has the ability to enable or disable public registration.

These changes will enhance the usability and configurability of the application, providing a more streamlined experience for both administrators and users.

## Motivation and Context

This change is required to address certain limitations and improve the functionality of the application. The current implementation lacks flexibility in terms of configuring the application and requires repetitive setup steps for administrators and users. By introducing a multi-login option and a Docker build dependency verifier, this pull request aims to enhance the user interface (UI) and streamline the setup process.

The motivation behind these changes is to provide users with more control over their configuration path and enable them to reset the admin account and other user accounts if needed. Deleting the ".cfgi" file will allow users to choose a new configuration path, while deleting the "users.json" file will facilitate the setup of the admin account and all other accounts.

By allowing users to delete the ".cfgi" file while preserving user credentials, the proposed changes eliminate the need to set up the admin account every time. Similarly, deleting the "users.json" file while retaining the configuration eliminates the requirement to configure the application repeatedly.

The availability of different setup config options, such as "No Login," "Single-User Login," "Multi-User Private Registration," and "Multi-User Public Registration," provides administrators and users with more flexibility in configuring the application according to their specific requirements.

Overall, these improvements enhance the usability and configurability of the application, addressing the limitations in the current implementation and providing a more streamlined experience for administrators and users.

## How has this been tested?

The changes proposed in this pull request have undergone comprehensive testing to ensure their functionality and compatibility with the existing codebase. The testing process involved various environments and scenarios to validate the effectiveness of the changes. Here is a detailed description of the testing approach:

1. **Local Docker Instance Testing:**
   - A local Docker instance was spun up to perform live local testing.
   - The changes were deployed within this Docker environment to simulate real-world usage.
   - Extensive testing was conducted to verify the behavior and functionality of the application within the Docker container.
   - This testing approach aimed to ensure that the changes work seamlessly in a containerized environment, providing accurate results and maintaining stability.

2. **Demo Distributions Testing:**
   - Several demo distributions were created to represent different usage scenarios.
   - These demo distributions were utilized to thoroughly test the changes across various setups and configurations.
   - The application was tested within each demo distribution to identify any potential issues or conflicts.
   - Multiple test cases were executed, covering different user interactions, login scenarios, and configuration options.
   - Through this testing, the changes were validated for their correctness, reliability, and compatibility with different distributions.

3. **Bug-Free Verification:**
   - The testing process aimed to identify and address any existing bugs or issues.
   - Throughout the testing phase, no bugs were found, indicating the robustness of the changes and their successful integration with the codebase.
   - The absence of bugs in the tested environments reinforces the reliability and stability of the proposed modifications.

By conducting thorough testing in a local Docker instance and multiple demo distributions, and by ensuring the absence of any bugs, the changes have been verified for their effectiveness and compatibility. The testing process has provided confidence in the reliability and stability of the modifications, assuring that they will perform as intended in various usage scenarios.

## Types of changes

The code in this pull request introduces the following types of changes. Please put an `x` in the boxes that apply:

- [ ] Bug fix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Enhancement or optimization (improves existing functionality/performance)
- [ ] Documentation update
- [ ] Other (please specify):

Changes visible to users:

- [ X] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [X ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [X ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [ ] My code follows the code style of this project and passes `yarn run lint`.
- [X ] My change requires a change to the documentation.
- [X ] My change works!

### CODE REVIEW

**Comment by Josh-XT** [comment]
Unable to merge with the docker files, they're duplicating what is already in the `docker` folder.

**Comment by rm4453** [comment]
There are new additions in Dockerfile && Dockerfile-streamlit, which need to be implemented in all docker files.
image2
image

**Comment by localagi** [comment]
@Josh-XT assign to me for co-working with @rm4453 

part of https://github.com/Josh-XT/Agent-LLM/issues/383

**Comment by Josh-XT** [comment]
Okay take a look at how I did PR #393 

I've completely modified the streamlit app to split each section into its own page and file.  MUCH easier to maintain without a 900 line file.  Please take a look and follow suit with how I built those page classes to add yours in if you can, it should be a lot easier now.

**Pull request closed without merging**
