### PR TITLE
update gpt4free to V2

### PR DESCRIPTION
**Pull request by ostix360**
# Description
update gpt4free to V2
use the v2 as explain in the gpt4free

## Types of changes

Changes visible to users:

- [ ] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [ ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [ ] My code follows the code style of this project and passes `yarn run lint`.
- [ ] My change requires a change to the documentation.
- [x] My change works!

### CODE REVIEW

**Comment by Josh-XT** [comment]
Do they automatically rotate now?  This PR would remove our entire rotation system for GPT4Free.

**Comment by ostix360** [comment]
It doesn't do it automatically 
I'm reimplementing the rotation

**Comment by ostix360** [comment]
One thing that I have delete is the while true in the instruct function so if all provider failed it return nothing. 
I don't think that the while true is great because try again and again even after 10 sec is useless to do it indefinitely 
And I remove also all provider that need auth. 
The old create_account is used for UseLess and Poe provider that g4f v2 doesn't handle any more. 
So the auth need more change that can be add later I think.

**Comment by Josh-XT** [comment]
Thanks!

**Pull request merged**
