### PR TITLE
Fix cicd docker cache (test)

### PR DESCRIPTION
**Pull request by lgwacker**
# Description

## Types of changes

Changes visible to users:

- [ ] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [ ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [ ] My code follows the code style of this project and passes `yarn run lint`.
- [ ] My change requires a change to the documentation.
- [ ] My change works!

### CODE REVIEW

**Comment by localagi** [comment]
@lgwacker cool - is there an comparison between the build? Why is registry cache better than gha? Can youn enlighten / send me a link?

**Comment by localagi** [comment]
https://docs.docker.com/build/ci/github-actions/cache/

looks like our gha should be fine. Also i experience on other projects the build time going down to <1min on subsequent builds, so the caching seems to work.

**Comment by localagi** [comment]
Also, the env variable you added somehow contradicts the caching config?

https://docs.docker.com/build/cache/backends/inline/

**Comment by localagi** [comment]
from latest builds, just seen:
```
#6 [stage-0 1/7] FROM docker.io/library/python:3.10-slim-bullseye@sha256:fd86924ba14682eb11a3c244f60a35b5dfe3267cbf26d883fb5c14813ce926f1
#6 resolve docker.io/library/python:3.10-slim-bullseye@sha256:fd86924ba14682eb11a3c244f60a35b5dfe3267cbf26d883fb5c14813ce926f1 done
#6 DONE 0.0s
#7 importing cache manifest from gha:5778630503048881827
```
so it works.

**Comment by localagi** [comment]
image
Working fine.... subsequent builds with small code changes....mostly running tests, the actual builds are done in 2 mins
image

**Comment by Josh-XT** [comment]
So is this good to merge @localagi  ?

**Pull request closed without merging**
