### PR TITLE
Re-Introduce poetry

### PR DESCRIPTION
**Pull request by localagi**
# Description

- get rid of dumb pip requirements txt
- all transferred from requirements.txt => pyproject.toml | setup.py => pyproject.toml | manifest.in => pyproject.toml & more
- use more intelligent dependency solving manager
- Seen https://python-poetry.org/docs/ on some AI projects, so tried it out
- works great
- Builds are reproducable and burning fast

Already found some version conflicts. Solved most of them.
One left, see https://github.com/xtekky/gpt4free/pull/604
To make it work, it temporarily uses my forked repo (PR branch)

## Motivation and Context

Want to make it run
- fixed the gpt4free dependency problems (requests)
- fixed the protobuf problem with streamlit (some dep wants to pull some lower dependency)
- fixed "get all versions of spacy to determin a correct version" (takes 1h on fresh venv)

## How has this been tested?

Locally on the branch specified

## Types of changes

Changes visible to users:

- [ ] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [x] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [x] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [x] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [x] My code follows the code style of this project and passes `yarn run lint`.
- [x] My change requires a change to the documentation.
- [x] My change works!

### CODE REVIEW

**Comment by localagi** [comment]
fixes also https://github.com/Josh-XT/AGiXT/issues/462

**Comment by Josh-XT** [comment]
Version file is also referenced by FastAPI, that will need changed for this to work.  Deleting the file will likely cause errors.

**Comment by localagi** [comment]
> Version file is also referenced by FastAPI, that will need changed for this to work. Deleting the file will likely cause errors.

On it.

**Comment by localagi** [comment]
@Josh-XT ready for review

**Comment by localagi** [comment]
refs

**Pull request closed without merging**
