### PR TITLE
Use local model loader as submodule to cut dependency volume in half

### PR DESCRIPTION
**Pull request by localagi**
# Description

Just a proposal, probably not necessary.

I came up with this, because i was debugging some docker related issues (unexpected exits on some hardware).
But as of now, it might not be some cpu-flag specific compilations on github runners.

So this is for reference and discussion if there are any benefits.

It does something good: It reduces the interference of providers loaded on startup. (Maybe it's too late, but it seems e.g. sentence transformers is doing some stuff even if not used, only because the agent provider is registered.)

Current state: Still docker-testing both variants. Default-full-blown and with modules. 

Note: Given we want the submodule (like autoGPTQ does with llama and triton) - it is described as "runtime addon dependencies" in poetry - we can still build any wanted version with docker: small (roundabout 1.ish GB) and full (roundabout 2.5ish GB).

PS: Such dependency updates always go by `poetry lock --no-update` to prevent unwanted bugs/changes in this fast-moving space. Keeps the lockfile changes still readable also.

## Types of changes

Changes visible to users:

- [ ] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [ ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [ ] My code follows the code style of this project and passes `yarn run lint`.
- [ ] My change requires a change to the documentation.
- [ ] My change works!

### CODE REVIEW

**Comment by localagi** [comment]
refs https://github.com/Josh-XT/AGiXT/issues/462

**Comment by localagi** [comment]
refs https://github.com/Josh-XT/AGiXT/issues/462

**Comment by localagi** [comment]
@Josh-XT I faced weird docker errors, specifically `exited with 132` errors. After hours of debugging, i can *guess* its about the sentence transformers. 
Doing a lightweight build without the additional deps needed for local runs makes it run for me.

Background: Docker just uses the CPU directly. My CPU seems too new, so some cpu features have changed. The provider deps rely on some instructions forcing my docker to exit. Reducing CPU-dependent libs in those builds would help a lot

**Comment by Josh-XT** [comment]
Sentence transformers is our primary embedding method with Chroma

**Comment by localagi** [comment]
> Sentence transformers is our primary embedding method with Chroma

So what is supposed to happen when the dependencies are changed like proposed?

**Pull request closed without merging**
