### PR TITLE
Enable Poetry-based installation on Apple Silicon

### LINKED ISSUE #566: Installing on Apple Silicon results in "Unable to find installation candidates for torch (2.0.1+cpu)"
### Description

Steps to reproduce:
1. poetry self update 1.5.0
2. export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
3. poetry install --with gpt4free

Actual results:
Command fails with "Unable to find installation candidates for torch (2.0.1+cpu)"

Root cause:
Insufficient markers in pyproject.toml - does not match Apple Silicon:
```
torch = [
  { markers = "platform_machine == 'x86_64' and sys_platform == 'linux'", version = "^2.0.1", source = "pytorch.org"},
  { markers = "platform_machine == 'aarch64' or sys_platform == 'win32'", version = "^2.0.1", source = "PyPI" }
]
```

Suggested solution:
Default to PyPi rather than only specifying it for aarch64 win32:
```
torch = [
  { markers = "platform_machine == 'x86_64' and sys_platform == 'linux'", version = "^2.0.1", source = "pytorch.org"},
  { version = "^2.0.1", source = "PyPI" }
]
```

### Steps to Reproduce the Bug

1. poetry install --with gpt4free

### Expected Behavior

Deps installed

### Operating System

- [ ] Linux
- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using poetry
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

### PR DESCRIPTION
**Pull request by motin**
# Description

[Default to PyPi for torch rather than only specifying it for aarch64 win32](https://github.com/Josh-XT/AGiXT/commit/45ccbb78f35d59d95c2ce96b9b5cb14e52b7ad5b)

## Motivation and Context

Fixes #566 

## How has this been tested?

Ran the steps to reproduce in the latest main branch, resulting in the original error:

```
  • Installing torch (2.0.1+cpu): Failed

  RuntimeError

  Unable to find installation candidates for torch (2.0.1+cpu)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/chooser.py:76 in choose_for
       72│
       73│             links.append(link)
       74│
       75│         if not links:
    →  76│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       77│
       78│         # Get the best link
       79│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       80│
```

Then ran the steps to reproduce in the fix branch and it succeeded:

```
$ poetry install --with gpt4free
Installing dependencies from lock file

Package operations: 214 installs, 1 update, 0 removals

  • Installing attrs (23.1.0)
  • Installing six (1.16.0)
  • Installing async-generator (1.10)
  • Installing h11 (0.14.0)
  • Installing idna (3.4)
  • Installing markupsafe (2.1.2)
  • Installing mdurl (0.1.2)
  • Installing numpy (1.24.3)
  • Installing outcome (1.2.0)
  • Installing pyrsistent (0.19.3)
  • Installing python-dateutil (2.8.2)
  • Installing pytz (2023.3)
  • Installing smmap (5.0.0)
  • Installing sniffio (1.3.0)
  • Installing sortedcontainers (2.4.0)
  • Installing tzdata (2023.3)
  • Installing catalogue (2.0.8)
  • Installing certifi (2023.5.7)
  • Installing charset-normalizer (3.1.0)
  • Installing decorator (5.1.1)
  • Installing entrypoints (0.4)
  • Installing exceptiongroup (1.1.1)
  • Installing frozenlist (1.3.3)
  • Installing gitdb (4.0.10)
  • Installing jinja2 (3.1.2)
  • Installing jsonschema (4.17.3)
  • Installing markdown-it-py (2.2.0)
  • Installing mpmath (1.3.0)
  • Installing multidict (6.0.4)
  • Installing pandas (2.0.1)
  • Installing pyasn1 (0.5.0)
  • Installing pycparser (2.21)
  • Installing pygments (2.15.1)
  • Installing pysocks (1.7.1)
  • Installing toolz (0.12.0)
  • Installing trio (0.22.0)
  • Installing typing-extensions (4.6.2)
  • Installing wsproto (1.2.0)
  • Installing urllib3 (1.26.16)
  • Installing zipp (3.15.0)
  • Installing aiosignal (1.3.1)
  • Installing altair (4.2.2)
  • Installing anyio (3.6.2)
  • Installing async-timeout (4.0.2)
  • Installing blinker (1.6.2)
  • Installing cachetools (5.3.0)
  • Installing cffi (1.15.1)
  • Installing click (8.1.3)
  • Installing cymem (2.0.7)
  • Installing filelock (3.12.0)
  • Installing fsspec (2023.5.0)
  • Installing gitpython (3.1.31)
  • Installing humanfriendly (10.0)
  • Installing importlib-metadata (6.6.0)
  • Installing murmurhash (1.0.9)
  • Installing networkx (3.1)
  • Installing packaging (23.1)
  • Installing pillow (9.5.0)
  • Installing protobuf (3.20.3)
  • Installing pyarrow (12.0.0)
  • Installing pyasn1-modules (0.3.0)
  • Installing pydantic (1.10.8)
  • Installing pydeck (0.8.0)
  • Installing pympler (1.0.1)
  • Installing pyparsing (3.0.9)
  • Installing pyyaml (6.0)
  • Installing requests (2.31.0)
  • Installing rich (13.3.5)
  • Installing rsa (4.9)
  • Installing srsly (2.4.6)
  • Installing sympy (1.12)
  • Installing tenacity (8.2.2)
  • Installing toml (0.10.2)
  • Installing tornado (6.3.2)
  • Installing tqdm (4.65.0)
  • Installing trio-websocket (0.10.2)
  • Installing tzlocal (5.0.1)
  • Installing validators (0.20.0)
  • Installing yarl (1.9.2)
  • Installing aiohttp (3.8.4)
  • Installing backoff (2.2.1)
  • Installing blis (0.7.9)
  • Installing coloredlogs (15.0.1)
  • Installing confection (0.0.4)
  • Installing cryptography (38.0.4)
  • Installing flatbuffers (23.5.26)
  • Installing google-auth (2.19.0)
  • Installing googleapis-common-protos (1.59.0)
  • Installing httpcore (0.17.2)
  • Installing httplib2 (0.22.0)
  • Installing httptools (0.5.0)
  • Installing huggingface-hub (0.14.1)
  • Installing joblib (1.2.0)
  • Installing lz4 (4.3.2)
  • Installing monotonic (1.6)
  • Installing preshed (3.0.8)
  • Installing psutil (5.9.5)
  • Installing oauthlib (3.2.2)
  • Installing pydub (0.25.1)
  • Installing pyperclip (1.8.2)
  • Installing python-dotenv (1.0.0)
  • Installing random-username (1.0.2)
  • Installing rapidfuzz (3.0.0)
  • Installing regex (2023.5.5)
  • Installing scipy (1.9.3)
  • Installing selenium (4.9.1)
  • Updating setuptools (67.7.2 -> 67.8.0)
  • Installing smart-open (6.3.0)
  • Installing socksio (1.0.0)
  • Installing starlette (0.27.0)
  • Installing speechrecognition (3.8.1)
  • Installing streamlit (1.22.0)
  • Installing threadpoolctl (3.1.0)
  • Installing tokenizers (0.13.3)
  • Installing torch (2.0.1)
  • Installing typer (0.7.0)
  • Installing uvloop (0.17.0)
  • Installing wasabi (1.1.1)
  • Installing watchfiles (0.19.0)
  • Installing wcwidth (0.2.6)
  • Installing websockets (11.0.3)
  • Installing wrapt (1.15.0)
  • Installing zstandard (0.21.0)
  • Installing accelerate (0.19.0)
  • Installing aiofiles (23.1.0)
  • Installing async-tio (1.3.2)
  • Installing bingimagecreator (0.3.0)
  • Installing clickhouse-connect (0.5.25)
  • Installing cohere (4.6.0)
  • Installing colorama (0.4.6)
  • Installing curl-cffi (0.5.6)
  • Installing deprecated (1.2.14)
  • Installing discord-py (2.2.3)
  • Installing duckdb (0.8.0)
  • Installing fake-useragent (1.1.3)
  • Installing fastapi (0.95.2)
  • Installing google-api-core (2.11.0)
  • Installing google-auth-httplib2 (0.1.0)
  • Installing greenlet (2.0.1)
  • Installing hnswlib (0.7.0)
  • Installing httpx (0.24.1)
  • Installing jsonlines (3.1.0)
  • Installing langcodes (3.3.0)
  • Installing levenshtein (0.21.0)
  • Installing loguru (0.7.0)
  • Installing mailgw-temporary-email (0.0.2)
  • Installing names (0.3.0)
  • Installing nltk (3.8.1)
  • Installing onnxruntime (1.15.0)
  • Installing openai (0.27.7)
  • Installing openaiauth (1.0.2)
  • Installing overrides (7.3.1)
  • Installing pathy (0.10.1)
  • Installing pdfminer-six (20221105)
  • Installing posthog (3.0.1)
  • Installing prompt-toolkit (3.0.38)
  • Installing pycryptodome (3.18.0)
  • Installing pyee (9.0.4)
  • Installing pyjwt (2.7.0)
  • Installing pymailtm (1.1.1)
  • Installing pynacl (1.5.0)
  • Installing pypasser (0.0.5)
  • Installing python-http-client (3.3.7)
  • Installing random-password-generator (2.2.0)
  • Installing requests-oauthlib (1.3.1)
  • Installing requests-toolbelt (1.0.0)
  • Installing retrying (1.3.4)
  • Installing scikit-learn (1.2.2)
  • Installing sentencepiece (0.1.99)
  • Installing soupsieve (2.4.1)
  • Installing spacy-legacy (3.0.12)
  • Installing spacy-loggers (1.0.4)
  • Installing starkbank-ecdsa (2.2.0)
  • Installing streamlit-chat (0.0.2.2 ffb0583)
  • Installing thinc (8.1.10)
  • Installing tiktoken (0.4.0)
  • Installing tls-client (0.2.1)
  • Installing torchvision (0.15.2)
  • Installing transformers (4.29.2)
  • Installing twocaptcha (0.0.1)
  • Installing uritemplate (4.1.1)
  • Installing uvicorn (0.22.0)
  • Installing wand (0.6.11)
  • Installing websocket-client (1.5.2)
  • Installing wonderwords (2.2.0)
  • Installing anthropic (0.2.9)
  • Installing bcrypt (4.0.1)
  • Installing beautifulsoup4 (4.12.2)
  • Installing captcha-solver (0.1.5)
  • Installing chromadb (0.3.25)
  • Installing discord (2.2.3)
  • Installing docker (6.1.2)
  • Installing docx2txt (0.8)
  • Installing duckduckgo-search (3.3.0)
  • Installing edgegpt (0.6.7)
  • Installing google-api-python-client (2.87.0)
  • Installing google-auth-oauthlib (1.0.0)
  • Installing googlebard (1.1.3)
  • Installing gpt4free (0.1.0 6598265)
  • Installing gtts (2.3.2)
  • Installing hugchat (0.0.6.2)
  • Installing instructorembedding (1.0.1)
  • Installing llama-cpp-python (0.1.55)
  • Installing nomic (1.1.6)
  • Installing pdfplumber (0.9.0)
  • Installing playsound (1.2.2)
  • Installing playwright (1.33.0)
  • Installing pygithub (1.58.2)
  • Installing revchatgpt (5.2.0)
  • Installing semantic-kernel (0.2.9.dev0)
  • Installing sendgrid (6.10.0)
  • Installing sentence-transformers (2.2.2)
  • Installing spacy (3.5.3)
  • Installing tweepy (4.14.0)
  • Installing webdriver-manager (3.8.6)

Installing the current project: AGiXT (v1.1.81-beta)
```

## Types of changes

Changes visible to users:

- [x] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [ ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [ ] My code follows the code style of this project and passes `yarn run lint`. <-- Missing yarn script so no
- [ ] My change requires a change to the documentation.
- [x] My change works!

### CODE REVIEW

**Comment by localagi** [comment]
Sadly, the current proposed solution will break the amd64 builds the way they are probably.

Please test the change also on x86 machine to make sure build behaves like wanted.

**Comment by localagi** [comment]
@motin please post the results of 
`platform.machine()`
and 
`sys.platform()`
on your silicon machine (run in a python shell, maybe import beforehand)

**Comment by motin** [comment]
arm64, darwin

Interesting, the solution doesn't change the source for aarch64 win32, but to be more defensive, I am happy to change this to:
```
torch = [
  { markers = "platform_machine == 'x86_64' and sys_platform == 'linux'", version = "^2.0.1", source = "pytorch.org"},
  { markers = "platform_machine == 'aarch64' or sys_platform == 'win32'", version = "^2.0.1", source = "PyPI" },
  { markers = "sys_platform == 'darwin' and platform_machine == 'arm64'", version = "^2.0.1", source = "PyPI" },
  { version = "^2.0.1", source = "PyPI" }
]
```

Wdyt?

**Comment by localagi** [comment]
> { markers = "platform_machine == 'aarch64' or sys_platform == 'win32'", version = "^2.0.1", source = "PyPI" },

Change this line
`  { markers = "platform_machine == 'aarch64' or sys_platform == 'win32'", version = "^2.0.1", source = "PyPI" }, `
to 
`  { markers = "platform_machine == 'aarch64' or platform_machine == 'arm64' or sys_platform == 'win32'", version = "^2.0.1", source = "PyPI" }, `

And see if it works. Should be able to stay with the two lines :)

**Comment by localagi** [comment]
Just for clarification, this should work:
```
torch = [
  { markers = "platform_machine == 'x86_64' and sys_platform == 'linux'", version = "^2.0.1", source = "pytorch.org"},
  { markers = "platform_machine == 'aarch64' or platform_machine == 'arm64' or sys_platform == 'win32'", version = "^2.0.1", source = "PyPI"}
]
```

**Comment by motin** [comment]
Tried it locally, poetry install works but poetry lock --no-update fails with:

```
$ poetry lock --no-update
Resolving dependencies... (3.5s)

maximum recursion depth exceeded while calling a Python object
```

**Comment by localagi** [comment]
> Tried it locally, poetry install works but poetry lock --no-update fails with:
> 
> ```
> $ poetry lock --no-update
> Resolving dependencies... (3.5s)
> 
> maximum recursion depth exceeded while calling a Python object
> ```

I'll try here on my machine

**Comment by localagi** [comment]
> Tried it locally, poetry install works but poetry lock --no-update fails with:
> 
> ```
> $ poetry lock --no-update
> Resolving dependencies... (3.5s)
> 
> maximum recursion depth exceeded while calling a Python object
> ```

On my side it works (i am on poetry 1.5.1 atm). Given the proposed changes i do get only a changed lock hash.

I'll try on my odroid n2 - some arm64 machine and see if it's some weird selection issue of poetry.

**Comment by localagi** [comment]
@motin Tried on my arm64 machine. Failed with the same error you faced. Was on poetry 1.5.0.
`pip install -U poetry` upgraded to 1.5.1 and the error was gone.

**Comment by localagi** [comment]
Also changed the markers in poetry.lock correctly now.

**Comment by motin** [comment]
Indeed, works on 1.5.1!

**Pull request merged**
