### PR TITLE
use liteLLM for providers - OpenAI, Anthropic, HuggingFace, Azure, VertexAI, Cohere etc

### PR DESCRIPTION
**Pull request by ishaan-jaff**
# Description
I noticed this repo maintains a providers directory for all llms. Instead of maintaining and adding to the providers directory litellm can simplify maintaining and adding new LLM models 

litellm https://github.com/BerriAI/litellm - is a simple & light package to call OpenAI, Azure, Cohere, Anthropic API Endpoints

Here's a sample of how it's used:

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

## Types of changes

Changes visible to users:

- [ ] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [ ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [x] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [ ] My code follows the code style of this project and passes `yarn run lint`.
- [x] My change requires a change to the documentation.
- [ ] My change works!

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@Josh-XT can you please take a look at this PR when you get the chance. ? 😊 

Happy to add more tests / docs if this initial commit looks good 

From looking at your repo - using litellm will simplify maintaining multiple LLM API providers + adding new models

**Comment by Josh-XT** [comment]
Hello @ishaan-jaff ! It looks like a nice project. We have a few more providers currently and a decent framework for managing them (everything could be better!), but it certainly would be nice to not maintain all of the providers some day.  I had even considered splitting off the providers part to a separate project similar to your litellm because of all of the work I have put into it, but I haven't had the time.  One of our niches has been to have the ability to generate text with just about any provider or model as is.  I don't get provider requests often and when I do, I usually make it pretty quickly unless there is some issue or too much reverse engineering required.  Most that either have a python package or are a simple REST API call aren't too terrible to manage until people start changing what their API endpoints are doing.

While I appreciate the offer, I have our current providers in good working order right now and don't want to poke the bees nest (potentially break anything) or send off these API calls through another python package if I can avoid it.  All of that said, feel free to learn from what we have with our providers and use anything that will help you move litellm forward.  It might be the best option in the future for managing the providers, I'm just okay with what is working now for now.

**Comment by Josh-XT** [comment]
> sounds great, thanks for the feedback !
> 
> Noticed you use starchat beta from hugging face Do you plan on adding more HF models soon? eg. meta-llama/Llama-2-7b-hf ?


I just have the Starchat agent there as an example really.  I personally use this for most of my own local model assistance: https://huggingface.co/OpenAssistant/llama2-13b-orca-8k-3319

**Comment by krrishdholakia** [comment]
hey @Josh-XT thank you for your feedback. I noticed in `huggingchat` you just had 2 chat models implemented. There's several great finetuned llama-2 implementations. Why the restriction?

**Comment by Josh-XT** [comment]
> hey @Josh-XT thank you for your feedback. I noticed in `huggingchat` you just had 2 chat models implemented. There's several great finetuned llama-2 implementations. Why the restriction?

The real answer is just that I didn't know that yet and haven't updated it.  I don't use all of the providers, a lot of them are updated by community contributions as updates come out.  I only use OpenAI for anything that I'm doing that is important, Ooba with local models for local model testing.

**Pull request closed without merging**
