### PR TITLE
fixes #497

### LINKED ISSUE #497: Make docker images for pull requests tagged correctly
### Description

Currently the build fails bc the pipeline does not know how to name the pr correctly

### Steps to Reproduce the Bug

just see the latest runs of the pipeline on PRs (release and main pushes are fine!)

### Expected Behavior

- have a docker image tagged with :pr-123 for the PR number
- also have multarch disabled on PR builds to save build time

### Actual Behavior

Fails

### Additional Context / Screenshots

@Josh-XT  can be assigned to me 

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

### PR DESCRIPTION
**Pull request by localagi**
# Description

- build arm64 only on release and manual trigger ==eqals== only amd64 builds on PR and main pushes
- tag PR docker releases correctly, provide full test pipeline and green checkmarks

## Types of changes

Changes visible to users:

- [ ] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [ ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [ ] My code follows the code style of this project and passes `yarn run lint`.
- [ ] My change requires a change to the documentation.
- [ ] My change works!

### CODE REVIEW

**Comment by localagi** [comment]
https://github.com/Josh-XT/AGiXT/issues/497

**Comment by localagi** [comment]
wip...

**Comment by Josh-XT** [comment]
Let me know whenever you want me to merge it.

**Comment by localagi** [comment]
Opened a bug for help: https://github.com/docker/build-push-action/issues/870

**Comment by localagi** [comment]
@Josh-XT how can i issue a docker build on this?

**Comment by Josh-XT** [comment]
I can merge if you want

**Pull request closed without merging**
