### PR TITLE
Add transformers requirement for Petals provider

### PR DESCRIPTION
**Pull request by ostix360**
# Description

Add transformer v4.31 for petal provider
Define  self.workspace_restricted =False as default in file for learning for #930 

## Types of changes

Changes visible to users:

- [x] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [ ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ ] **Breaking change** (prefix: `feat!!` or `fix!!` - fix or feature that would cause existing functionality to not work as expected)

Internal changes:

- [ ] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ ] **Tests** (prefix: `test` - additions and improvements to unit tests and the smoke tests)
- [ ] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)

## Checklist

- [x] My code follows the code style of this project and passes `yarn run lint`.
- [ ] My change requires a change to the documentation.
- [x] My change works!

### CODE REVIEW

**Comment by Josh-XT** [comment]
Do you know if Petals has a separate API and container that we could use as an alternative to directly importing transformers and/or torch?  I removed the transformers dependency because Petals is the only provider that uses it, it should install if not installed upon first use.  Most people aren't using that provider but everyone has to download the 5.56GB container that runs with docker if transformers is required.  Removing it reduced the size of the container to 1.31GB.

I also fixed the read file issue in #932 - default behavior should be to restrict the working directory.

**Comment by ostix360** [comment]
Okay so just for one provider it's too much.
I found [this](https://github.com/petals-infra/chat.petals.dev) I just read very quickly and it seem to be an API.

**Comment by ostix360** [comment]
I tried to deal with the http api but the api return this "AssertionError: please set max_length or max_new_tokens (not both)" whereas 'max_length' is only set on the payload

**Comment by Josh-XT** [comment]
> I tried to deal with the http api but the api return this "AssertionError: please set max_length or max_new_tokens (not both)" whereas 'max_length' is only set on the payload

I wouldn't set max_length, just set max_new_tokens.  Take a look at how I am doing it in the OpenAI provider for handling max_new_tokens.

**Comment by ostix360** [comment]
> I tried to deal with the http api but the api return this "AssertionError: please set max_length or max_new_tokens (not both)" whereas 'max_length' is only set on the payload

Okay so I update to new max token and find this issue (header was extra)
I also add the possibility to change the model and extra  parameters (temps etc) based on openai provider 👍 

In the petal chat api they mention:
>If you develop your own web app, you can use our endpoint at https://chat.petals.dev/api/... for research and development, >then set up your own backend for production using the commands above.
>
>Note: We do not recommend using the endpoint at https://chat.petals.dev/api/... in production. It has a limited throughput, >and we may pause or stop it any time.
so if most of people doesn't use it, it will not be a problem

One last thing,  instead of raising an error it can be only logged if you prefer.

**Pull request merged**
